// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyL_VdX_wXUT-vikYSYmCbnPjN62-Q0NA',
    appId: '1:1067007418899:web:9fa2a1763ef1cc855855e6',
    messagingSenderId: '1067007418899',
    projectId: 'careplusplus-b8166',
    authDomain: 'careplusplus-b8166.firebaseapp.com',
    storageBucket: 'careplusplus-b8166.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaYoMkibzHv2O-bSA8Yw_sB7s8aNbC1E',
    appId: '1:1067007418899:android:097ec59e3cfb56515855e6',
    messagingSenderId: '1067007418899',
    projectId: 'careplusplus-b8166',
    storageBucket: 'careplusplus-b8166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCboM_bWih0qgZl2gC_G7eZBZMvrfSZuIs',
    appId: '1:1067007418899:ios:994cda25684e12065855e6',
    messagingSenderId: '1067007418899',
    projectId: 'careplusplus-b8166',
    storageBucket: 'careplusplus-b8166.firebasestorage.app',
    iosBundleId: 'com.example.careplus',
  );
}
